export const FETCH_GET_ALL_AUDIOS_REQUEST = 'FETCH_GET_ALL_AUDIOS_REQUEST';
export const FETCH_GET_ALL_AUDIOS_SUCCESS = 'FETCH_GET_ALL_AUDIOS_SUCCESS';
export const FETCH_GET_ALL_AUDIOS_FAILURE = 'FETCH_GET_ALL_AUDIOS_FAILURE';

export const FETCH_GET_MY_AUDIOS_REQUEST = 'FETCH_GET_ALL_AUDIOS_REQUEST';
export const FETCH_GET_MY_AUDIOS_SUCCESS = 'FETCH_GET_ALL_AUDIOS_SUCCESS';
export const FETCH_GET_MY_AUDIOS_FAILURE = 'FETCH_GET_ALL_AUDIOS_FAILURE';
