export default [
  {
    id: 2310,
    playlistId: 4,
    url: 'https://soundcloud.com/deejayfewzofficial/between-moments',
    image: 'https://i1.sndcdn.com/artworks-6hcPORxfLzvnUsZj-petAVg-t500x500.jpg',
    performer: 'FEWZ',
    title: 'Between Moments',
    album: 'Way of Life',
  },
  {
    id: 21,
    playlistId: 1,
    url: 'https://soundcloud.com/toni-alvarez/toni-alvarez-accusol-original-mix',
    image: 'https://i1.sndcdn.com/avatars-000633624417-khekdk-t500x500.jpg',
    performer: 'Toni Alvarez',
    title: 'Accusol (Original mix)',
    album: '',
  },
  {
    id: 22,
    playlistId: 2,
    url: 'https://soundcloud.com/deejayfewzofficial/levitate',
    image: 'https://i1.sndcdn.com/artworks-000283537604-m4m3ta-t500x500.jpg',
    performer: 'FEWZ',
    title: 'Levitate ',
    album: '',
  },
  {
    id: 33,
    playlistId: 3,
    url: 'https://soundcloud.com/deejayfewzofficial/endless',
    image: 'https://i1.sndcdn.com/artworks-000387479538-5okbzw-t500x500.jpg',
    performer: 'FEWZ',
    title: 'Endless ',
    album: '',
  },
  {
    id: 54,
    playlistId: 4,
    url: 'https://soundcloud.com/justicehardcore/4-wild-love-out-now',
    image: 'https://i1.sndcdn.com/artworks-gxM8y1A4ROzPvI5a-ttXBvQ-t500x500.jpg',
    performer: 'Justice Hardcore',
    title: 'Wild Love ',
    album: '',
  },
  {
    id: 75,
    playlistId: 5,
    url: 'https://soundcloud.com/deejayfewzofficial/written-in-stone-soon-on-itunes-spotify',
    image: 'https://i1.sndcdn.com/artworks-000171906567-na6f00-t500x500.jpg',
    performer: 'FEWZ',
    title: 'Written In Stone ',
    album: '',
  },
  {
    id: 69,
    playlistId: 6,
    url: 'https://soundcloud.com/justicehardcore/latsol4remix',
    image: 'https://i1.sndcdn.com/artworks-GbTcQDeAZtNTPf5P-uVWBNQ-t500x500.jpg',
    performer: 'Nobody',
    title: 'Love At The Speed Of Light ',
    album: '',
  },
  {
    id: 547,
    playlistId: 1,
    url: 'https://soundcloud.com/derdritteraum/tb-303-test-run',
    image: 'https://i1.sndcdn.com/artworks-000043909673-ciiy5j-t500x500.jpg',
    performer: 'Der Dritte Raum',
    title: 'TB-303 Test Run ',
    album: '',
  },
  {
    id: 3458,
    playlistId: 2,
    url: 'https://soundcloud.com/mangesh-gandini/tb-303',
    image: 'https://i1.sndcdn.com/artworks-000074268054-io8xdp-t500x500.jpg',
    performer: 'Mangesh Gandini',
    title: 'TB 303 ',
    album: '',
  },
  {
    id: 679,
    playlistId: 3,
    url: 'https://soundcloud.com/summersoundsmusic/we-are-one-inspire-summer-sounds-release',
    image: 'https://i1.sndcdn.com/artworks-000177730300-fguvmb-t500x500.jpg',
    performer: 'We Are One',
    title: 'Inspire',
    album: '',
  },
];
